name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: libzmusic_player.so
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: zmusic_player.dll
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: libzmusic_player.dylib

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Toolchain
      run: rustup install stable && rustup default stable
    - name: Add target for Apple Silicon
      if: matrix.os == 'macos-latest'
      run: rustup target add aarch64-apple-darwin
    - name: Add target for Intel
      if: matrix.os == 'macos-latest'
      run: rustup target add x86_64-apple-darwin

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
    
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build project
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.artifact_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        retention-days: 30
